In [ ]:
#Step 1: Import libraies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Step 2: Create dataframe
data = {
    'Age': [25,30,np.nan,40,35],
    'salary': [25000,14000,25000,np.nan,30000],
    'Gender': ['Male','Female','Male','Female','Male'],
    'Purchase': ['Yes','No','Yes','Yes','No']
}
df=pd.DataFrame(data)
df

    Age   salary  Gender Purchase
0  25.0  25000.0    Male      Yes
1  30.0  14000.0  Female       No
2   NaN  25000.0    Male      Yes
3  40.0      NaN  Female      Yes
4  35.0  30000.0    Male       No

In [ ]:
#to Check Null values
df.isnull().sum()

Age         1
salary      1
Gender      0
Purchase    0
dtype: int64

In [ ]:
#use simple imputer to handle null values
from sklearn.impute import SimpleImputer
SI=SimpleImputer()
df[['Age']]=SI.fit_transform(df[['Age']])
df[['salary']]=SI.fit_transform(df[['salary']])
df
#fit : tain your model and transform : apply the changes

    Age   salary  Gender Purchase
0  25.0  25000.0    Male      Yes
1  30.0  14000.0  Female       No
2  32.5  25000.0    Male      Yes
3  40.0  23500.0  Female      Yes
4  35.0  30000.0    Male       No

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
#Label encoder to convert categorical values in the nuerical

In [ ]:
df['Purchase'] = le.fit_transform(df['Purchase'])
df

    Age   salary  Gender  Purchase
0  25.0  25000.0    Male         1
1  30.0  14000.0  Female         0
2  32.5  25000.0    Male         1
3  40.0  23500.0  Female         1
4  35.0  30000.0    Male         0

In [ ]:
df['Gender'] = le.fit_transform(df['Gender'])
df

    Age   salary  Gender  Purchase
0  25.0  25000.0       1         1
1  30.0  14000.0       0         0
2  32.5  25000.0       1         1
3  40.0  23500.0       0         1
4  35.0  30000.0       1         0

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [ ]:
df['Gender']=ohe.fit_transform(df[['Gender']]).toarray()
df

    Age   salary  Gender  Purchase
0  25.0  25000.0     0.0         1
1  30.0  14000.0     1.0         0
2  32.5  25000.0     0.0         1
3  40.0  23500.0     1.0         1
4  35.0  30000.0     0.0         0

In [ ]:
X = df[['Age','salary']] #features or input
y = df['Purchase'] #target or output

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns = data.feature_names)

In [ ]:
# add a target coulumn
df['target'] = data.target
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [ ]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [ ]:
#Add  null values
df.loc[5:15, 'mean radius'] = None
df.loc[5:15, 'mean perimeter'] = None

In [ ]:
#now handle null values
from sklearn.impute import SimpleImputer
SI = SimpleImputer(strategy='mean')
df[['mean radius', 'mean perimeter']] = SI.fit_transform(df[['mean radius','mean perimeter']])

In [ ]:
# Check outliers and handle them
q1 = df['mean radius'].quantile(0.25)
q3 = df['mean radius'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

In [ ]:
outliers = df[(df['mean radius'] < lower_bound) | (df['mean radius'] > upper_bound)]
outliers.shape

(15, 31)

In [ ]:
# Eliminate the outliers
df = df[(df['mean radius'] < lower_bound) & (df['mean radius'] > upper_bound)]

In [ ]:
## Enconding
df['tumor_size'] = pd.cut(
   df['mean radius'],
   bins = [0,12,18,30],
   labels = ['small','medium','large']
)

df['hospital_type'] = ['private' if i%2 == 0 else 'govt' for i in range (len(df))]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['tumor_size'] = le.fit_transform(df['tumor_size'])
df['hospital_type'] = le.fit_transform(df['hospital_type'])